### ISSUE TITLE
Deauther isnt shown in FZ

### ISSUE THREAD

**Issue by Solilord** [Timmotools/flipperzero_esp8266_deautherv2#1]
Hey! 

Thanks for your work! 

Iam trying to get you Plugin running on my Zero.
Roguemaster compiles fine. 
But even with adding "APPS_wifi_deauther" under basic_plugins in application.fam there is no menu point on flipper :/

What am i doing wrong?

**Comment by Solilord** [comment]
nvm. 
Iam dumb as hell. 
It was there...

**Comment by Timmotools** [comment]
Im glad you worked it out. I have just updated this repo because I had forgotten to add the enable 5v in this version. If you cloned this version you may need to update. if you are using the version inside roguemaster then you will be fine as its an older version with it still enabled.

**Comment by Solilord** [comment]
Yeah, I bothered some minutes with FZ crashing.
But then I realized, 5V was off 😅

I will do my first Test with deauthing on Monday :)
Maybe a small thing I didn’t figured out yet:
how (more: where) can I configure SSID/Pw and parameters for WebInterface?

ESP32 and NRF modules are also on its way from china. 

Edit: after thinking about it, it probably has to be done in ESP8266 Deauth-Fw..
Yeah I will look through Arduino IDE tmrw
I already did compile it by myself

**Comment by Timmotools** [comment]
the settings can be done on the FZ. scroll down towards the bottom and select left/right to go through the options i have for the deauther. these are just some of the options available from the command line. using "get settings" will show all things configurable over the serial. 

yeah I was testing with the usb cable still connected to the FZ and that causes the 5v to stay powered. that was my bad haha.
