### ISSUE TITLE
how to make it on flipper main menu

### ISSUE THREAD

**Issue by JackTheFine** [Timmotools/flipperzero_esp8266_deautherv2#3]
(not an issue again sorry) is it possible for me to add this as a menu screen thing so i don't have to go into applications i can just click from the home screen like clock nfc etc.

**Comment by Timmotools** [comment]
There used to be. I'm not sure about now that the extra plugins are now faps.

Without testing myself, I would suggest the following steps:
download the firmware source (either roguemaster, unleashed or OG)
download this sourcecode and put the folder "wifi_deauther" into the "applications/plugins/" folder (if not using roguemaster)
edit the file application.fam
change the line apptype=FlipperAppType.EXTERNAL, to apptype=FlipperAppType.APP,
compile the firmware and load.

Let me know how you go.

**Comment by Timmotools** [comment]
okay got it. 

move the folder "wifi_deauther" to the "/applications/main/"

edit "/applications/main/wifi_deauther/application.fam" to look like this: 
App(
    appid="ESP8266_Wifi_Deauther",
    name="[ESP8266] WiFi (Deauther)",
    apptype=FlipperAppType.APP,
    entry_point="wifi_deauther_app",
    cdefines=["APP_WIFI_deauther"],
    requires=["gui"],
    stack_size=2 * 1024,
    order=15,
    icon="A_Sub1ghz_14",
)

Then you need to add the line into "/applications/main/application.fam" under the unirfremix line.
"ESP8266_Wifi_Deauther",

Then compile and upload to the flipper. 

See how you go with that one.

**Comment by JackTheFine** [comment]
thank you!!! ![image](https://user-images.githubusercontent.com/112029550/205905991-e817e944-eee1-4b78-b26d-07544b800d85.jpeg)
